spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 270436218674-srvfetl5ks8dridnldjj532js5csags7
            client-secret: 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
            redirect-uri: http://localhost:8080/api/auth/google/callback
            scope:
              - email
              - profile

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/phongtro
    username: postgres
    password: 24042004
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update # Options: create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  servlet:
    multipart:
          max-file-size: ${app.upload.max-file-size:10MB}
          max-request-size: ${app.upload.max-request-size:10MB}
          enabled: true

#  # Connection Pool Configuration (HikariCP - default in Spring Boot)
#  datasource:
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
#      idle-timeout: 300000
#      connection-timeout: 20000
#      leak-detection-threshold: 60000

# Server Configuration
server:
  port: 8080
# Logging Configuration
logging:
  level:
    com.phongtro247backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  show-actuator: true

# File Upload Configuration

# Application specific properties
app:
  jwt:
    secret: ${JWT_SECRET:winrn4J+9L4swlKwKkk4HhoNLMJxb/MGR/T54+mo95c=}
    expiration: 86400000 # 24 hours in milliseconds
  upload:
    path: ${UPLOAD_PATH:./uploads}
    max-file-size: 10MB
    max-request-size: 10MB
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  security:
    bcrypt-strength: 12
