-- Insert default room utilities if they don't exist
INSERT IGNORE INTO room_utility (name) VALUES 
('Wifi'),
('Điều hòa'),
('Tủ lạnh'),
('Máy giặt'),
('Nóng lạnh'),
('Giường'),
('Tủ quần áo'),
('Bàn học'),
('Ghế'),
('Kệ sách'),
('Bếp gas'),
('Lò vi sóng'),
('Tivi'),
('Máy sấy tóc'),
('Gương'),
('Cửa sổ'),
('Ban công'),
('Thang máy'),
('Bảo vệ 24/7'),
('Camera an ninh'),
('Chỗ để xe'),
('Gần trường học'),
('Gần bệnh viện'),
('Gần chợ'),
('Gần siêu thị');
